### ISSUE TITLE
Disable total recall improvement

### ISSUE THREAD

**Issue by JaniKervinen** [AURAPluginsLtd/Access-Virus-Editor#35]
**Is your feature request related to a problem? Please describe.**
One would like to disable total recall by default so that it won't mess up the hardware data when editor is loaded from channel strip setting or such.

**Describe the solution you'd like**
Add option to utilities -> editor preferences menu where you can disable total recall by default on all instances.

**Comment by Guod3** [comment]
Is the idea behind this to have a situation where when you create an instance of VirusHE in your DAW session, it does not initialise all the multi patches in your Virus?
Presumably, when you load VirusHE into a DAW session with a (DAW supported) template or preset instantiation, the **utilities -> editor preferences menu** setting will **not** be in the "disable total recall" state, so that the instance will load the synth with all the patches and data that were stored when the template or preset was created?

**Comment by JaniKervinen** [comment]
@Guod3 Idea is to disable total recall in a way that it does not send the data, but saves the data in the project template if any data is modified.
