### ISSUE TITLE
Licence file

### ISSUE THREAD

**Issue by BrownCharlie555** [AURAPluginsLtd/Access-Virus-Editor#43]
Hello, 

How to get hold of a licence file for the Virus TI editor I purchased from Mystery Island Music in 2021.
Thank you.

Regards,

**Comment by TheLazyGeekGuy** [comment]
On the website i guess ... ?

**Comment by JaniKervinen** [comment]
@BrownCharlie555  You can download the license from https://auraplugins.com website or https://www.mysteryislands-music.com website.
License is downloadable from /downloads/ page. 

For future, "forum" is for questions, chat and talks rather than opening issues on the board: https://github.com/AURAPluginsLtd/Access-Virus-Editor/discussions
