### ISSUE TITLE
Latest build (27/2/2023) loads existing project with Midi ports reset and all patches INIT

### ISSUE THREAD

**Issue by Guod3** [AURAPluginsLtd/Access-Virus-Editor#50]
**Describe the bug**
Simply installing the latest VHC has resulted a situation where loading existing projects fails because MIDI in and out ports are OFF and all the parts are INIT.

Obviously DONT save your project in this state or you'll lose your project sounds.

I will have to re-install the last version which was working acceptably for me.

**Comment by Guod3** [comment]
I can also report that the GUI was unresponsive to mouse clicks until I free-floated then restored the open GUI in it's normally docked state.
I have restored my system to the previous build (10/2022) and all is well again.
I would respectfully request that all BETA releases be released as such: That they are installed and operate **alongside** the previous version until such a time as they are stable, when they can be released as a legitimate update.
This avoids the gross inconvenience of having to locate and reinstall working versions when the beta breaks things...

**Comment by mwbhtx** [comment]
I've kinda always had this problem...Virus on a mac is hell. Anybody wanna buy a Virus TI2 desktop?

**Comment by JaniKervinen** [comment]
Build 9024 is back online for those who had issues with build 9028. We are looking into the issue.
For us, Virus TI and Virus C has worked like a dream in macOS. Just avoid using usb, since TI uses USB1 protocol and prioritizes audio streams, midi stream is secondary. And on top of that, Virus TIOS 5.x broke the arp clock as far as we've heard. (We never use arp, so can't tell for sure).

**Comment by JaniKervinen** [comment]
build 9031 available now, let me know if that works out ok!
